//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graftech.ControlAcceso
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosEmpresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentosEmpresa()
        {
            this.EmpresaDocumentos = new HashSet<EmpresaDocumentos>();
        }
    
        public int Id { get; set; }
        public string NombreDocumento { get; set; }
        public Nullable<int> Activo { get; set; }
        public Nullable<bool> Obligatorio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpresaDocumentos> EmpresaDocumentos { get; set; }
    }
}
