//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graftech.ControlAcceso
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participante_Curso
    {
        public int participante_id { get; set; }
        public int curso_id { get; set; }
        public int estatus_id { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual estatus estatus { get; set; }
        public virtual Participante Participante { get; set; }
    }
}
