//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Denso.ControlAcceso
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Participante()
        {
            this.ParticipanteDocumentos = new HashSet<ParticipanteDocumentos>();
        }
    
        public int id { get; set; }
        public Nullable<int> empresa_id { get; set; }
        public string nombre { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public string correoElectronico { get; set; }
        public string telefono { get; set; }
        public string certificaciones { get; set; }
        public string direccion { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string foto { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
        public string IMSS { get; set; }
        public string cartaNoAntecedentes { get; set; }
        public string registroIMSS { get; set; }
        public string usuarioCanvas { get; set; }
        public string passwordCanvas { get; set; }
        public string matricula { get; set; }
        public Nullable<bool> credencial { get; set; }
        public Nullable<bool> activo { get; set; }
        public string pago_sua { get; set; }
        public string pago_sua_archivo { get; set; }
        public string contactoOpcional { get; set; }
        public string contactoTelefono { get; set; }
        public string estatus { get; set; }
        public string CurpFile { get; set; }
        public string Departamento { get; set; }
        public string Grupo { get; set; }
        public string puesto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipanteDocumentos> ParticipanteDocumentos { get; set; }
    }
}
